import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { ExternalLink, Sparkles, Users, Image as ImageIcon } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { cn } from "@/lib/utils";

interface PublicImage {
  id: string;
  public_url: string;
  prompt: string;
  created_at: string;
  settings?: any;
}

const PublicGallery = () => {
  const [images, setImages] = useState<PublicImage[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeFilter, setActiveFilter] = useState<string>("all");
  const navigate = useNavigate();

  const filters = [
    { id: "all", label: "All Images", icon: ImageIcon },
    { id: "product", label: "Products", icon: Sparkles },
    { id: "lifestyle", label: "Lifestyle", icon: Users },
  ];

  useEffect(() => {
    fetchPublicImages();
  }, []);

  const fetchPublicImages = async () => {
    try {
      const { data, error } = await supabase
        .from("generated_images")
        .select("id, public_url, prompt, created_at, settings")
        .eq("public_showcase", true)
        .order("created_at", { ascending: false })
        .limit(12);

      if (error) throw error;
      setImages(data || []);
    } catch (error) {
      console.error("Error fetching public images:", error);
    } finally {
      setLoading(false);
    }
  };

  const filteredImages = images.filter((image) => {
    if (activeFilter === "all") return true;
    const prompt = image.prompt.toLowerCase();
    
    if (activeFilter === "product") {
      return prompt.includes("product") || prompt.includes("bottle") || prompt.includes("package");
    }
    if (activeFilter === "lifestyle") {
      return prompt.includes("lifestyle") || prompt.includes("person") || prompt.includes("scene");
    }
    return true;
  });

  const handleTryCreating = () => {
    navigate("/auth");
  };

  const handleOpenImage = (imageUrl: string) => {
    window.open(imageUrl, '_blank');
  };

  if (loading) {
    return (
      <section className="py-16 lg:py-24 bg-muted/30">
        <div className="container-responsive px-4">
          <div className="text-center space-y-4 mb-12">
            <Skeleton className="h-10 w-64 mx-auto" />
            <Skeleton className="h-6 w-96 mx-auto" />
          </div>
          
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {Array.from({ length: 8 }).map((_, i) => (
              <Card key={i} className="overflow-hidden">
                <Skeleton className="aspect-square w-full" />
                <CardContent className="p-4">
                  <Skeleton className="h-4 w-full mb-2" />
                  <Skeleton className="h-3 w-20" />
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>
    );
  }

  return (
    <section className="py-16 lg:py-24 bg-muted/30">
      <div className="container-responsive px-4">
        {/* Header */}
        <div className="text-center space-y-4 mb-12">
          <h2 className="text-3xl lg:text-4xl font-bold text-foreground">
            Created by Our Community
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Discover amazing images generated by our users. Join thousands of creators transforming their ideas into stunning visuals.
          </p>
          
          {/* Stats */}
          <div className="flex justify-center items-center gap-8 pt-4">
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">10K+</div>
              <div className="text-sm text-muted-foreground">Images Created</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">500+</div>
              <div className="text-sm text-muted-foreground">Active Creators</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">95%</div>
              <div className="text-sm text-muted-foreground">Satisfaction Rate</div>
            </div>
          </div>
        </div>

        {/* Filters */}
        <div className="flex justify-center mb-8">
          <div className="flex gap-2 p-1 bg-background rounded-lg border">
            {filters.map((filter) => {
              const Icon = filter.icon;
              return (
                <Button
                  key={filter.id}
                  variant={activeFilter === filter.id ? "default" : "ghost"}
                  size="sm"
                  onClick={() => setActiveFilter(filter.id)}
                  className="gap-2"
                >
                  <Icon className="h-4 w-4" />
                  {filter.label}
                </Button>
              );
            })}
          </div>
        </div>

        {/* Gallery Grid */}
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mb-12">
          {filteredImages.map((image, index) => (
            <Card
              key={image.id}
              className={cn(
                "group overflow-hidden border-2 border-transparent hover:border-primary/50 transition-all duration-300 cursor-pointer",
                "hover:shadow-lg hover:scale-[1.02]"
              )}
              onClick={() => handleOpenImage(image.public_url)}
            >
              <div className="relative aspect-square overflow-hidden">
                <img
                  src={image.public_url}
                  alt={`Generated: ${image.prompt.slice(0, 50)}...`}
                  className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                  loading={index < 4 ? "eager" : "lazy"}
                />
                
                {/* Overlay */}
                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors duration-300 flex items-center justify-center">
                  <Button
                    variant="secondary"
                    size="sm"
                    className="opacity-0 group-hover:opacity-100 transition-opacity duration-300 gap-2"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleOpenImage(image.public_url);
                    }}
                  >
                    <ExternalLink className="h-4 w-4" />
                    View Full Size
                  </Button>
                </div>
              </div>
              
              <CardContent className="p-4">
                <p className="text-sm text-muted-foreground line-clamp-2 mb-2">
                  {image.prompt}
                </p>
                <div className="flex items-center justify-between">
                  <Badge variant="secondary" className="text-xs">
                    {new Date(image.created_at).toLocaleDateString()}
                  </Badge>
                  {image.settings?.style && (
                    <Badge variant="outline" className="text-xs">
                      {image.settings.style}
                    </Badge>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* CTA Section */}
        <div className="text-center space-y-6 pt-8 border-t border-border/50">
          <div className="space-y-2">
            <h3 className="text-xl font-semibold text-foreground">
              Ready to Create Your Own?
            </h3>
            <p className="text-muted-foreground">
              Join our community and start generating amazing images today.
            </p>
          </div>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              size="lg" 
              onClick={handleTryCreating}
              className="gap-2"
            >
              <Sparkles className="h-4 w-4" />
              Start Creating for Free
            </Button>
            <Button 
              variant="outline" 
              size="lg"
              onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
            >
              Learn More
            </Button>
          </div>
        </div>

        {/* Empty State */}
        {!loading && filteredImages.length === 0 && (
          <div className="text-center py-12">
            <ImageIcon className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-foreground mb-2">
              No images found
            </h3>
            <p className="text-muted-foreground">
              Try selecting a different filter or check back later for new content.
            </p>
          </div>
        )}
      </div>
    </section>
  );
};

export default PublicGallery;