// SecurePublicGallery.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence, useReducedMotion } from "framer-motion";

/** ---------- Local asset loader (Vite) ---------- */
type PublicImage = { id: string; url: string; alt: string };

const localPngs = import.meta.glob("@/assets/landing_gallery/*.png", {
  eager: true,
  as: "url",
}) as Record<string, string>;

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function toImages(map: Record<string, string>): PublicImage[] {
  return Object.entries(map)
    .sort((a, b) => {
      const an = parseInt(a[0].match(/(\d+)\.png$/)?.[1] ?? "0", 10);
      const bn = parseInt(b[0].match(/(\d+)\.png$/)?.[1] ?? "0", 10);
      return an - bn;
    })
    .map(([path, url], i) => ({
      id: `local-${i + 1}`,
      url,
      alt: path.split("/").pop() || `image-${i + 1}`,
    }));
}

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

/** ---------- Config ---------- */
const PAGE_SIZE = 12;     // 12 images per “page”
const AUTO_MS = 14500;     // auto-advance cadence
const TRANSITION_MS = 550;

/** ---------- Component ---------- */
export default function SecurePublicGallery() {
  const reduceMotion = useReducedMotion();

  // Build once: load → shuffle → paginate
  const pages = useMemo(() => {
    const randomized = shuffle(toImages(localPngs));
    const pool =
      randomized.length >= PAGE_SIZE
        ? randomized
        : Array.from({ length: Math.ceil(PAGE_SIZE / randomized.length) })
            .flatMap(() => randomized)
            .slice(0, PAGE_SIZE);
    return chunk(pool, PAGE_SIZE);
  }, []);

  const [pageIdx, setPageIdx] = useState(0);
  const intervalRef = useRef<number | null>(null);

  // Auto-advance (pause when tab hidden)
  useEffect(() => {
    const start = () => {
      stop();
      intervalRef.current = window.setInterval(() => {
        setPageIdx((p) => (p + 1) % pages.length);
      }, AUTO_MS);
    };
    const stop = () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
    };
    const onVis = () => (document.hidden ? stop() : start());

    start();
    document.addEventListener("visibilitychange", onVis);
    return () => {
      stop();
      document.removeEventListener("visibilitychange", onVis);
    };
  }, [pages.length]);

  if (!pages.length) {
    return (
      <section className="py-16 lg:py-24 bg-muted/30">
        <div className="container-responsive px-4 text-center">
          <h3 className="text-lg font-semibold">No images found</h3>
          <p className="text-muted-foreground">
            Add PNGs to <code>/assets/landing_gallery</code> and rebuild.
          </p>
        </div>
      </section>
    );
  }

  // Per-tile motion
  const item = {
    initial: { opacity: 0, y: reduceMotion ? 0 : 12, scale: reduceMotion ? 1 : 0.995 },
    animate: { opacity: 1, y: 0, scale: 1, transition: { duration: TRANSITION_MS / 1000 } },
    exit: { opacity: 0, y: reduceMotion ? 0 : -12, scale: reduceMotion ? 1 : 0.995, transition: { duration: TRANSITION_MS / 1000 } },
  };
  const container = {
    animate: { transition: { staggerChildren: 0.04, delayChildren: 0.05 } },
    exit: { transition: { staggerChildren: 0.03, staggerDirection: -1 } },
  };

  const current = pages[pageIdx];

  return (
    <section className="py-16 lg:py-24 bg-muted/30" id="explore">
      <div className="container-responsive px-4">
        {/* Header */}
        <div className="text-center space-y-4 mb-10">
          <h2 className="text-3xl lg:text-4xl font-bold text-foreground">
            Created by Our Community
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Discover amazing images generated by our users. Join hundreds of creators transforming their ideas into stunning visuals.
          </p>
        </div>

        {/* Masonry container: columns-based layout */}
        <AnimatePresence mode="wait">
          <motion.div
            key={`page-${pageIdx}`}
            variants={container}
            initial="animate"
            animate="animate"
            exit="exit"
            className="
              columns-2 md:columns-3 lg:columns-4 gap-0
            "
          >
            {current.map((img, i) => (
              <motion.figure
                key={`${img.id}-${pageIdx}-${i}`}
                variants={item}
                className="
                  break-inside-avoid
                  overflow-hidden
                  border border-border/50 bg-background
                "
              >
                {/* Native aspect ratio preserved */}
                <img
                  src={img.url}
                  alt={img.alt}
                  className="w-full h-auto block"
                  loading="lazy"
                />
              </motion.figure>
            ))}
          </motion.div>
        </AnimatePresence>

        <p className="text-center text-xs text-muted-foreground mt-6">
          Rotates every {(AUTO_MS / 1000).toFixed(0)}s.
        </p>
      </div>
    </section>
  );
}
