import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Sparkles, Users, Image as ImageIcon } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { cn } from "@/lib/utils";
import { BeforeAfterSlider } from "@/components/ui/before-after";

interface PublicImage {
  id: string;
  public_url: string;
  prompt: string;
  created_at: string;
  settings?: any;
  source_url?: string;
}

const SecurePublicGallery = () => {
  const [images, setImages] = useState<PublicImage[]>([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    fetchPublicImages();
  }, []);

  const fetchPublicImages = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('public-gallery');
      
      if (error) {
        console.error("Error fetching public images:", error);
        setImages([]);
      } else {
        setImages(data?.images || []);
      }
    } catch (error) {
      console.error("Error fetching public images:", error);
      setImages([]);
    } finally {
      setLoading(false);
    }
  };

  const handleTryCreating = () => {
    navigate("/account");
  };


  if (loading) {
    return (
      <section className="py-16 lg:py-24 bg-muted/30" id="explore">
        <div className="container-responsive px-4">
          <div className="text-center space-y-4 mb-12">
            <Skeleton className="h-10 w-64 mx-auto" />
            <Skeleton className="h-6 w-96 mx-auto" />
          </div>
          
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {Array.from({ length: 8 }).map((_, i) => (
              <Card key={i} className="overflow-hidden">
                <Skeleton className="aspect-square w-full" />
                <CardContent className="p-4">
                  <Skeleton className="h-4 w-full mb-2" />
                  <Skeleton className="h-3 w-20" />
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>
    );
  }

  return (
    <section className="py-16 lg:py-24 bg-muted/30">
      <div className="container-responsive px-4">
        {/* Header */}
        <div className="text-center space-y-4 mb-12">
          <h2 className="text-3xl lg:text-4xl font-bold text-foreground">
            Created by Our Community
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Discover amazing images generated by our users. Join thousands of creators transforming their ideas into stunning visuals.
          </p>
        </div>

        {/* Gallery Grid */}
        <div className="grid gap-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mb-12">
          {images.map((image, index) => (
            <Card
              key={image.id}
              className={cn(
                "group overflow-hidden border-2 border-transparent hover:border-primary/50 transition-all duration-300",
                "hover:shadow-lg hover:scale-[1.02]"
              )}
            >
              <div className="aspect-square">
                <BeforeAfterSlider
                  beforeImage={image.source_url || image.public_url}
                  afterImage={image.public_url}
                  alt={`Generated: ${image.prompt.slice(0, 50)}...`}
                  className="w-full h-full"
                  grayscaleBefore={!image.source_url}
                />
              </div>
            </Card>
          ))}
        </div>

        {/* CTA Section */}
        <div className="text-center space-y-6 pt-8 border-t border-border/50">
          <div className="space-y-2">
            <h3 className="text-xl font-semibold text-foreground">
              Ready to Create Your Own?
            </h3>
            <p className="text-muted-foreground">
              Join our community and start generating amazing images today.
            </p>
          </div>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              size="lg" 
              onClick={handleTryCreating}
              className="gap-2"
            >
              <Sparkles className="h-4 w-4" />
              Start Creating for Free
            </Button>
            <Button 
              variant="outline" 
              size="lg"
              onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
            >
              Learn More
            </Button>
          </div>
        </div>

        {/* Empty State */}
        {!loading && images.length === 0 && (
          <div className="text-center py-12">
            <ImageIcon className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-foreground mb-2">
              No images found
            </h3>
            <p className="text-muted-foreground">
              Try selecting a different filter or check back later for new content.
            </p>
          </div>
        )}
      </div>
    </section>
  );
};

export default SecurePublicGallery;