import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.50.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      throw new Error("Missing authorization header");
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const lovableApiKey = Deno.env.get("LOVABLE_API_KEY");

    if (!lovableApiKey) {
      throw new Error("LOVABLE_API_KEY not configured");
    }

    const supabaseClient = createClient(supabaseUrl, supabaseServiceKey);
    
    const { data: { user }, error: authError } = await supabaseClient.auth.getUser(
      authHeader.replace("Bearer ", "")
    );

    if (authError || !user) {
      throw new Error("Unauthorized");
    }

    const { action, ...params } = await req.json();

    if (action === "uploadAndProcessModel") {
      return await uploadAndProcessModel(supabaseClient, user.id, params, lovableApiKey);
    } else if (action === "generateModelWithAI") {
      return await generateModelWithAI(supabaseClient, user.id, params, lovableApiKey);
    } else {
      throw new Error(`Unknown action: ${action}`);
    }
  } catch (error) {
    console.error("Error in create-base-model:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

async function uploadAndProcessModel(
  supabaseClient: any,
  userId: string,
  params: any,
  lovableApiKey: string
) {
  const { imageDataUrl, metadata } = params;
  const creditCost = 5;

  // Check credits
  const { data: creditCheck, error: creditError } = await supabaseClient.rpc(
    "deduct_user_credits",
    {
      p_user_id: userId,
      p_amount: creditCost,
      p_reason: "upload_base_model",
    }
  );

  if (creditError || !creditCheck?.success) {
    throw new Error(creditCheck?.error || "Insufficient credits");
  }

  try {
    // Process image with Gemini - remove background and replace with studio
    const prompt = `Remove the background from this image and replace it with: seamless light gray studio. Camera 50mm f/4 ISO200 1/125. Lighting: softbox 45° key + reflector fill, even exposure. Neutral expression, hands relaxed, fingers natural, head to toe visible, clean silhouette. Keep the person exactly as they are, only change the background.`;

    const geminiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${lovableApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: prompt },
              {
                type: "image_url",
                image_url: { url: imageDataUrl }
              }
            ]
          }
        ],
        modalities: ["image", "text"]
      })
    });

    if (!geminiResponse.ok) {
      throw new Error(`Gemini API error: ${geminiResponse.statusText}`);
    }

    const geminiData = await geminiResponse.json();
    const processedImageUrl = geminiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!processedImageUrl) {
      throw new Error("No image generated by Gemini");
    }

    // Convert base64 to blob
    const base64Data = processedImageUrl.split(",")[1];
    const imageBlob = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    // Upload to storage
    const timestamp = Date.now();
    const storagePath = `${userId}/${timestamp}-${metadata.name.replace(/[^a-zA-Z0-9]/g, "_")}.png`;
    
    const { error: uploadError } = await supabaseClient.storage
      .from("outfit-base-models")
      .upload(storagePath, imageBlob, {
        contentType: "image/png",
        upsert: false,
      });

    if (uploadError) throw uploadError;

    // Get public URL
    const { data: urlData } = supabaseClient.storage
      .from("outfit-base-models")
      .getPublicUrl(storagePath);

    // Create base model entry
    const { data: baseModel, error: dbError } = await supabaseClient
      .from("outfit_swap_base_models")
      .insert({
        user_id: userId,
        name: metadata.name,
        gender: metadata.gender,
        age_range: metadata.ageRange,
        body_type: metadata.bodyType,
        pose_type: metadata.poseType,
        skin_tone: metadata.skinTone,
        storage_path: storagePath,
        public_url: urlData.publicUrl,
        is_system: false,
        is_active: true,
      })
      .select()
      .single();

    if (dbError) throw dbError;

    return new Response(
      JSON.stringify({ success: true, baseModel }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    // Refund credits on failure
    await supabaseClient.rpc("refund_user_credits", {
      p_user_id: userId,
      p_amount: creditCost,
      p_reason: "upload_base_model_failed",
    });
    throw error;
  }
}

async function generateModelWithAI(
  supabaseClient: any,
  userId: string,
  params: any,
  lovableApiKey: string
) {
  const creditCost = 6;

  // Check credits
  const { data: creditCheck, error: creditError } = await supabaseClient.rpc(
    "deduct_user_credits",
    {
      p_user_id: userId,
      p_amount: creditCost,
      p_reason: "generate_ai_base_model",
    }
  );

  if (creditError || !creditCheck?.success) {
    throw new Error(creditCheck?.error || "Insufficient credits");
  }

  try {
    const { name, gender, ageRange, bodyType, height, skinTone, hair, eyes, pose, gentleSmile } = params;

    // Build the generation prompt
    const smileText = gentleSmile ? ", gentle smile" : "";
    const prompt = `Photorealistic full-body studio ${gender} model, age bracket ${ageRange}, height ${height} cm, body type ${bodyType}, skin tone ${skinTone}, hair ${hair.length} ${hair.texture} ${hair.color}, eyes ${eyes}. Pose: ${pose}${smileText}. Wardrobe baseline: seamless neutral-tone fitted bodysuit (no logos/patterns), barefoot. Background: seamless light gray studio. Camera 50mm f/4 ISO200 1/125. Lighting: softbox 45° key + reflector fill, even exposure. Neutral expression, hands relaxed, fingers natural, head to toe visible, clean silhouette. One subject only. Output 2048x3072, sRGB, 300dpi. Negative: lowres, blurry, jpeg artifacts, extra limbs, extra fingers, fused fingers, disfigured, distorted proportions, wet/oily skin, cleavage emphasis, lingerie, underwear straps, see-through fabric, strong face shadows, color cast, watermark, logo, text, border.`;

    console.log("Generating AI model with prompt:", prompt);

    const geminiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${lovableApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        modalities: ["image", "text"]
      })
    });

    if (!geminiResponse.ok) {
      const errorText = await geminiResponse.text();
      console.error("Gemini API error:", geminiResponse.status, errorText);
      throw new Error(`Gemini API error: ${geminiResponse.statusText}`);
    }

    const geminiData = await geminiResponse.json();
    const generatedImageUrl = geminiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!generatedImageUrl) {
      console.error("No image in Gemini response:", JSON.stringify(geminiData));
      throw new Error("No image generated by Gemini");
    }

    // Convert base64 to blob
    const base64Data = generatedImageUrl.split(",")[1];
    const imageBlob = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    // Upload to storage
    const timestamp = Date.now();
    const storagePath = `${userId}/${timestamp}-${name.replace(/[^a-zA-Z0-9]/g, "_")}.png`;
    
    const { error: uploadError } = await supabaseClient.storage
      .from("outfit-base-models")
      .upload(storagePath, imageBlob, {
        contentType: "image/png",
        upsert: false,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      throw uploadError;
    }

    // Get public URL
    const { data: urlData } = supabaseClient.storage
      .from("outfit-base-models")
      .getPublicUrl(storagePath);

    // Create base model entry
    const { data: baseModel, error: dbError } = await supabaseClient
      .from("outfit_swap_base_models")
      .insert({
        user_id: userId,
        name,
        gender: gender === "non-binary" ? "unisex" : gender,
        age_range: ageRange,
        body_type: bodyType,
        pose_type: pose,
        skin_tone: skinTone,
        storage_path: storagePath,
        public_url: urlData.publicUrl,
        is_system: false,
        is_active: true,
        metadata: {
          height,
          hair,
          eyes,
          gentleSmile,
          generatedWithAI: true,
        },
      })
      .select()
      .single();

    if (dbError) {
      console.error("Database insert error:", dbError);
      throw dbError;
    }

    console.log("AI model generated successfully:", baseModel.id);

    return new Response(
      JSON.stringify({ success: true, baseModel }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error in generateModelWithAI:", error);
    // Refund credits on failure
    await supabaseClient.rpc("refund_user_credits", {
      p_user_id: userId,
      p_amount: creditCost,
      p_reason: "generate_ai_base_model_failed",
    });
    throw error;
  }
}
