import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const GOOGLE_AI_KEY = Deno.env.get('GOOGLE_AI_API_KEY')

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    console.log('[TEST-GEMINI] Direct API test started')
    
    if (!GOOGLE_AI_KEY) {
      throw new Error('GOOGLE_AI_API_KEY environment variable is not set')
    }

    const { prompt, sourceImageUrl } = await req.json()
    
    if (!prompt) {
      throw new Error('Prompt is required')
    }

    console.log('[TEST-GEMINI] Making direct API call', { 
      hasSourceImage: !!sourceImageUrl, 
      promptLength: prompt.length 
    })

    let requestBody: any = {
      prompt: { text: prompt },
      imageGenerationConfig: {
        numberOfImages: 1,
        aspectRatio: "1:1",
        includeRaiBlockedPrompt: false,
        includeRaiInfoInResponse: false,
        safetySetting: "BLOCK_ONLY_HIGH",
        personGeneration: "DONT_ALLOW"
      }
    }

    // Handle source image if provided
    if (sourceImageUrl) {
      console.log('[TEST-GEMINI] Processing source image')
      const src = await fetch(sourceImageUrl)
      if (!src.ok) throw new Error(`Failed to fetch source image: ${src.status}`)
      
      const imageBuffer = await src.arrayBuffer()
      console.log('[TEST-GEMINI] Image buffer size:', imageBuffer.byteLength)
      
      // Safe base64 conversion for large images
      const uint8Array = new Uint8Array(imageBuffer)
      let binary = ''
      const chunkSize = 32768
      
      for (let i = 0; i < uint8Array.length; i += chunkSize) {
        const chunk = uint8Array.subarray(i, i + chunkSize)
        binary += String.fromCharCode.apply(null, Array.from(chunk))
      }
      
      const base64Image = btoa(binary)
      console.log('[TEST-GEMINI] Base64 conversion completed, length:', base64Image.length)
      
      requestBody.baseImage = {
        image: { bytesBase64Encoded: base64Image },
        imageEditInstruction: { text: prompt }
      }
    }

    // Make API call to Google Imagen-3.0
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0:generateImages`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${GOOGLE_AI_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
    })

    console.log('[TEST-GEMINI] API response status:', response.status)

    if (!response.ok) {
      const errorText = await response.text()
      console.error('[TEST-GEMINI] API error:', errorText)
      throw new Error(`Gemini API error: ${response.status} - ${errorText}`)
    }

    const result = await response.json()
    console.log('[TEST-GEMINI] API response received:', {
      hasGeneratedImages: !!result.generatedImages,
      imageCount: result.generatedImages?.length || 0
    })

    if (!result.generatedImages || result.generatedImages.length === 0) {
      throw new Error('No images generated by Gemini API')
    }

    const generatedImage = result.generatedImages[0]
    
    return new Response(JSON.stringify({
      success: true,
      image: {
        base64: generatedImage.bytesBase64Encoded,
        mimeType: generatedImage.mimeType || 'image/jpeg',
        prompt: prompt,
        hasSourceImage: !!sourceImageUrl
      },
      metadata: {
        apiResponse: result,
        timestamp: new Date().toISOString()
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })

  } catch (error) {
    console.error('[TEST-GEMINI] Error:', error)
    return new Response(JSON.stringify({
      success: false,
      error: error.message,
      timestamp: new Date().toISOString()
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })
  }
})