-- Add missing columns to image_jobs table
ALTER TABLE public.image_jobs 
ADD COLUMN IF NOT EXISTS progress INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS completed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS failed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS finished_at TIMESTAMP WITH TIME ZONE;