// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhqdamfisdbbcieqlpvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRocWRhbWZpc2RiYmNpZXFscHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzg2MzQsImV4cCI6MjA2NzY1NDYzNH0.RzNhA0P-mkVwOAl88xPX8ovPNj-WUOG-0Jw8OZbWM7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});